num: int = 10

def add_num(a: int, b: int) -> int:
    return a + b

r = add_num(10, 20)
print(r)
# stringを型定義したとしても、エラーは発生しない